version: '3.8'

services:
  db:
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ft_trans

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - db
    networks:
      - ft_trans
  
  front:
    build:
      context: front
      dockerfile: Dockerfile
    expose:
      - 3000
      - 443
      - 5500
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
    networks:
      - ft_trans


volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  ft_trans:
    driver: bridge
