# Generated by Django 3.2.11 on 2024-02-14 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0008_game_room_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('win_count', models.IntegerField(default=0)),
                ('lose_count', models.IntegerField(default=0)),
                ('fa_enabled', models.BooleanField(default=False)),
                ('online_status', models.BooleanField(default=False)),
                ('blocked', models.ManyToManyField(blank=True, related_name='blocked', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('game_room', models.ManyToManyField(blank=True, related_name='game_room', to='game.Game_Room')),
                ('received_friend_requests', models.ManyToManyField(blank=True, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('sended_friend_requests', models.ManyToManyField(blank=True, related_name='sended_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
