# Generated by Django 4.2.10 on 2024-02-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_profile_bio"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="logged",),
    ]
