# Generated by Django 4.2.10 on 2024-02-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_profile_logged"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default_profile_picture.jpg", upload_to="avatars/"
            ),
        ),
    ]
