# Generated by Django 3.2.11 on 2023-12-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20231221_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game_Message',
        ),
    ]
