# Generated by Django 3.2.11 on 2024-02-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_delete_game_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='game_room',
            name='user_l',
        ),
        migrations.RemoveField(
            model_name='game_room',
            name='user_r',
        ),
        migrations.AddField(
            model_name='game_room',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game_room',
            name='loser',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='game_room',
            name='score_guest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game_room',
            name='score_host',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game_room',
            name='user_guest',
            field=models.CharField(default='guest', max_length=100),
        ),
        migrations.AddField(
            model_name='game_room',
            name='user_host',
            field=models.CharField(default='host', max_length=100),
        ),
        migrations.AddField(
            model_name='game_room',
            name='winner',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
