# Generated by Django 3.2.11 on 2024-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20240210_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
